### ISSUE TITLE
Cannot share images from external app to Telegram

### ISSUE THREAD

**Issue by vanitasvitae** [slp/Telegram-FOSS#109]
Hi! I cannot share images from eg. Gallery to telegram anymore:

```
08-02 21:32:11.421 12800-12800/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.telegram.messenger, PID: 12800
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                       at java.util.regex.Matcher.reset(Matcher.java:177)
                                                       at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                       at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                       at org.telegram.ui.LaunchActivity.handleIntent(LaunchActivity.java:646)
                                                       at org.telegram.ui.LaunchActivity.onNewIntent(LaunchActivity.java:1366)
                                                       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1212)
                                                       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
                                                       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2545)
                                                       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2557)
                                                       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2566)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ExecInit.main(ExecInit.java:56)
                                                       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
08-02 21:32:11.422 12800-12800/? E/AndroidRuntime: Error reporting crash
                                                   java.lang.RuntimeException: Bad file descriptor
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:503)
                                                       at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4427)
                                                       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by ManuelLR** [comment]
This occurs with any file from external app. 
Example, share a pdf from Adobe Reader app or share a file from Download folder. 

_This occurs in Cyanogenmod 13.0 with Telegram version 3.10.1 (821) installed from F-Droid _

**Comment by slp** [comment]
Looking at the code, I think this could be related to our changes to support some alternatives to Google Maps.  @Bubu could you please take a look at this?

**Comment by Bubu** [comment]
I will take a look.

**Comment by vrillic** [comment]
Confirmed. Having same issue.

**Comment by Bubu** [comment]
I'm on vacation right now (I didn't get to finish this before I left.) It will be another week before I can have another look.

**Comment by brainscript** [comment]
Same issue. :(

**Comment by jinformatique** [comment]
same issue.

**Comment by Raltux** [comment]
I can confirm this bug report. "Free" Telegram branch from F-Droid is broken.
It is not possible to share pictures from my album, directly. Using image editors that are tagging their posts by ads is possible, however (I suppose the image is embedded in some environment, then).

It is not possible at all to post video files as video, for this reason. Just appending full size video files as attachments is possible. 

Workaround: Select attachment from within Telegram (exception: video files).

Workaround #2: Downgrade (uninstall was necessary in my case)
Workaround #3: Uninstall and switch to google play store (if installed)
Workaround #4: Get a woriking APK from somewhere.

For the next upstream release, there might be some privacy issues in the upstream:
1. If you are going to attach any file, there is a live image of your camera displayed (scarey!)
2. If you type any string containing a dot (full stop) - e.g.  t0p.s3cr37 - that string will run through Telegram's DNS & preview services, even before you submit the message!

**Comment by Bubu** [comment]
Should be fixed by new version on fdroid shortly.
