### ISSUE TITLE
Crash when long pressing emojis.

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#52]
Here is the logcat:
```
D/AndroidRuntime(15574): Shutting down VM
E/AndroidRuntime(15574): FATAL EXCEPTION: main
E/AndroidRuntime(15574): Process: org.telegram.messenger, PID: 15574
E/AndroidRuntime(15574): java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
E/AndroidRuntime(15574): 	at org.telegram.ui.Components.EmojiView$ImageViewEmoji$2.onLongClick(EmojiView.java:108)
E/AndroidRuntime(15574): 	at android.view.View.performLongClick(View.java:4828)
E/AndroidRuntime(15574): 	at android.view.View$CheckForLongPress.run(View.java:19855)
E/AndroidRuntime(15574): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(15574): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15574): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15574): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(15574): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15574): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15574): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(15574): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(15574): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
W/ActivityManager(  897):   Force finishing activity 1 org.telegram.messenger/org.telegram.ui.LaunchActivity
```

**Comment by slp** [comment]
Thanks @Bubu 

Do you think this bug justifies faking a 3.2.7 version?
