### ISSUE TITLE
Error Can not start application

### ISSUE THREAD

**Issue by huyduongtu** [slp/Telegram-FOSS#72]
Firstly, I run the application. It crashes with the following exception.
```
org.telegram.messenger.beta E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.telegram.messenger.beta, PID: 26673
java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean) (tried Java_org_telegram_tgnet_ConnectionsManager_native_1setJava and Java_org_telegram_tgnet_ConnectionsManager_native_1setJava__Z)
      at org.telegram.tgnet.ConnectionsManager.native_setJava(Native Method)
      at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:266)
      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4661)
      at android.app.ActivityThread.access$1500(ActivityThread.java:156)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:211)
      at android.app.ActivityThread.main(ActivityThread.java:5373)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```
I see that there are no .so files. I run ndk-build to build .so files. But it ends with the error below:

```
[armeabi] Compile arm    : tmessages.17 <= jni.c
In file included from D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/./jni.c:7:0:
D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/openssl/include/openssl/aes.h:1:1: error: expected identifier or '(' before '.' token
 ../../crypto/aes/aes.h
 ^
D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/./jni.c: In function 'Java_org_telegram_messenger_Utilities_aesIgeEncryption':
D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/./jni.c:51:5: error: unknown type name 'AES_KEY'
     AES_KEY akey;
     ^
D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/./jni.c:54:60: error: 'AES_DECRYPT' undeclared (first use in this function)
         AES_ige_encrypt(what, what, length, &akey, ivBuff, AES_DECRYPT);
                                                            ^
D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/./jni.c:54:60: note: each undeclared identifier is reported only once for each function it appears in
D:/AndroidStudioProjects/Telegram-FOSS/TMessagesProj/jni/./jni.c:57:60: error: 'AES_ENCRYPT' undeclared (first use in this function)
         AES_ige_encrypt(what, what, length, &akey, ivBuff, AES_ENCRYPT);
                                                            ^
```
I also run task `nativeLibToJar`. But It doesn't build out .so files.

**Comment by Bubu** [comment]
I guess the problem is that Windows does not recognize the symlinks in the `TMessagesProj/jni/openssl/include/openssl/`folder. See here: http://stackoverflow.com/questions/5917249/git-symlinks-in-windows

You could copy all .h files manually in that folder or make same NTFS symlinks/junctions. Or I guess someone could update the makefiles to not require the symlinked structure.

**Comment by kaprat** [comment]
Add ndk { abiFilters "armeabi", "armeabi-v7a", "x86", "mips" } in defaultConfig

defaultConfig {
...............
...............
ndk { abiFilters "armeabi", "armeabi-v7a", "x86", "mips" }
}
